openapi: 3.0.3
info:
  title: productpage
  description: |-
    Product Page API
  version: 'v1'
servers:
  - url: "http://localhost:8080"
  - url: "https://microcks-microcks.apps.cluster-l9nz6.dynamic.redhatworkshops.io/rest/productpage/v1"
paths: {}
